// server/config/colleges.js
// Maps email domain → official college name.
// The name here MUST match the `name` field in client/src/data/colleges.js exactly.

export const supportedColleges = {
  // IITs
  "iitb.ac.in":      "IIT Bombay",
  "iitd.ac.in":      "IIT Delhi",
  "iitg.ac.in":      "IIT Guwahati",
  "iitk.ac.in":      "IIT Kanpur",
  "iitkgp.ac.in":    "IIT Kharagpur",
  "iitm.ac.in":      "IIT Madras",
  "iitr.ac.in":      "IIT Roorkee",
  "iith.ac.in":      "IIT Hyderabad",
  "iitbbs.ac.in":    "IIT Bhubaneswar",
  "iitgn.ac.in":     "IIT Gandhinagar",
  "iitj.ac.in":      "IIT Jodhpur",
  "iitp.ac.in":      "IIT Patna",
  "iiti.ac.in":      "IIT Indore",
  "iitmandi.ac.in":  "IIT Mandi",
  "iitbhu.ac.in":    "IIT (BHU) Varanasi",
  "iitpkd.ac.in":    "IIT Palakkad",
  "iittp.ac.in":     "IIT Tirupati",
  "iitism.ac.in":    "IIT (ISM) Dhanbad",
  "iitbhilai.ac.in": "IIT Bhilai",
  "iitdh.ac.in":     "IIT Dharwad",
  "iitjammu.ac.in":  "IIT Jammu",
  "iitgoa.ac.in":    "IIT Goa",
  "iitrpr.ac.in":    "IIT Ropar",

  // NITs
  "mnnit.ac.in":        "MNNIT Allahabad",
  "nita.ac.in":         "NIT Agartala",
  "nitandhra.ac.in":    "NIT Andhra Pradesh",
  "nitap.in":           "NIT Arunachal Pradesh",
  "nitc.ac.in":         "NIT Calicut",
  "nitdelhi.ac.in":     "NIT Delhi",
  "nitdgp.ac.in":       "NIT Durgapur",
  "nitgoa.ac.in":       "NIT Goa",
  "nith.ac.in":         "NIT Hamirpur",
  "nitj.ac.in":         "NIT Jalandhar",
  "nitjsr.ac.in":       "NIT Jamshedpur",
  "nitk.ac.in":         "NIT Karnataka (Surathkal)",
  "nitkkr.ac.in":       "NIT Kurukshetra",
  "nitmanipur.ac.in":   "NIT Manipur",
  "nitm.ac.in":         "NIT Meghalaya",
  "nitmz.ac.in":        "NIT Mizoram",
  "nitnagaland.ac.in":  "NIT Nagaland",
  "nitp.ac.in":         "NIT Patna",
  "nitpy.ac.in":        "NIT Puducherry",
  "nitrr.ac.in":        "NIT Raipur",
  "nitrkl.ac.in":       "NIT Rourkela",
  "nits.ac.in":         "NIT Silchar",
  "nitsri.ac.in":       "NIT Srinagar",
  "nitt.edu":           "NIT Tiruchirappalli",
  "nituk.ac.in":        "NIT Uttarakhand",
  "nitw.ac.in":         "NIT Warangal",
  "mnit.ac.in":         "MNIT Jaipur",
  "manit.ac.in":        "MANIT Bhopal",
  "svnit.ac.in":        "SVNIT Surat",
  "vnit.ac.in":         "VNIT Nagpur",
  "nitsikkim.ac.in":    "NIT Sikkim",
};
